name: 'Build Extension'

on: push

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 1.8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Checkout submodules'
        uses: textbook/git-checkout-submodule-action@master
      - name: 'Install 32-bit dependencies'
        run: sudo apt-get install -y libc6-i386 lib32z1 lib32stdc++6
      - name: 'Build Extension Appinventor'
        run: ant extensions
        working-directory: appinventor
      - name: 'Upload Companion to Artifacts'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ steps.build_aix.outputs.file }}
          path: appinventor/components/build/extensions/${{ steps.build_aix.outputs.file }}
